name: food_favorite_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_test: ^9.0.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:


  uses-material-design: true

  assets:
    - assets/translations/

 